@startuml Movement

class Main {

}
class Navigator {
    + getCurrentRow(currentCell: String): int
    + getCurrentColumn(currentCell: String): int
    + handleCommand(command: String, currentCell: String): String
    - moveUp(currentCell: String): String
    - moveDown(currentCell: String): String
    - moveLeft(currentCell: String): String
    - moveRight(currentCell: String): String
}

Main -- Navigator 

@enduml
