@startuml Movement

[*] -right-> NoHayCaracter

state NoHayCaracter{
    [*] -down-> HayCaracter : Caracter introducido
}

state HayCaracter{
    [*] -right-> DeterminarDireccion
    DeterminarDireccion -down-> Mover : Producir movimiento
}
Mover -right-> [*]

@enduml

