@startuml

object "spreadsheet: Spreadsheet" as spreadsheet {
    - sheet : Sheet
    - movement : Movement
    - input : Scanner
    - rows : int
    - columns : int
}

object "cell: Cell" as cell {
    - x : int
    - y : int
    - cellValue : String
}

object "mathOperations: MathOperations" as mathOperations

object "menu: Menu" as menu

object "movement: Movement" as movement

object "settings: Settings" as settings

object "sheet: Sheet" as sheet {
    - sheetData : Cell[][]
    - currentCell : String
    - spacing : int
}

object "viewport: Viewport" as viewport

spreadsheet *-d-> sheet
spreadsheet *--> movement
spreadsheet -l-|> settings
spreadsheet --|> viewport
spreadsheet --|> mathOperations
spreadsheet -r-|> menu
movement --|> settings
viewport ..> sheet
viewport -|> settings
mathOperations ..> sheet
sheet -d-> cell

@enduml